# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(name: "Fill", score: 20)

Lyric.create(song_title: "Hotline Bling", genre:"Hip-Hop", artist:"Drake", api_id: 16632952, content:"You used to call me on my\nYou used to, you used to\nYeah\n\nYou used to call me on my cell phone\nLate night when you need my love\nCall me on my cell phone\nLate night when you need my love\nAnd I know when that hotline bling\nThat can only mean one thing\nI know when that hotline bling\nThat can only mean one thing\n\nEver since I left the city,\nYou got a reputation for yourself now\nEverybody knows and I feel left out\nGirl you got me down, you got me stressed out\n'Cause ever since I left the city,\nyou started wearing less and goin' out more\nGlasses of champagne out on the dance floor\nHangin' with some girls I've never seen before\n\nYou used to call me on my cell phone\nLate night when you need my love\n...\n\n******* This Lyrics is NOT for Commercial use *******\n(1409618378968)")
Lyric.create(song_title: "Baby Shark", genre:"Pop", artist:"Little Baby Bum Nursery Rhyme Friends", api_id: 17761020, content:"Baby Shark doo doo, doo doo doo doo\nBaby Shark doo doo, doo doo doo doo\nBaby Shark doo doo, doo doo doo doo\nBaby Shark\nMummy Shark doo doo, doo doo doo doo\nMummy Shark doo doo, doo doo doo doo\nMummy Shark doo doo, doo doo doo doo\nMummy Shark\nDaddy Shark doo doo, doo doo doo doo\nDaddy Shark doo doo, doo doo doo doo\nDaddy Shark doo doo, doo doo doo doo\nDaddy Shark\n...\n\n******* This Lyrics is NOT for Commercial use *******\n(1409618378968)")
Lyric.create(song_title: "Sk8er Boi", genre:"Pop", artist:"Avril Lavigne", api_id: 18360775, content:"He was a boy, she was a girl\nCan I make it any more obvious?\nHe was a punk, she did ballet\nWhat more can I say?\n\nHe wanted her\nShe'd never tell secretly she wanted him as well\nBut all of her friends stuck up their nose\nThey had a problem with his baggy clothes\n\nHe was a skater boy\nShe said see you later boy\nHe wasn't good enough for her\nShe had a pretty face but her head was up in space\nShe needed to come back down to earth\n\nFive years from now\nShe sits at home\nFeeding the baby she's all alone\nShe turns on TV\nGuess who she sees\nSkater boy rockin' up MTV\n\n...\n\n******* This Lyrics is NOT for Commercial use *******\n(1409618378968)")
Lyric.create(song_title: "Baby Got Back", genre:"Hip-Hop", artist:"Sir-Mix-A-Lot", api_id: 16744237, content:"Oh my god\nBecky, look at her butt\nIts so big\nShe looks like one of those rap guys girlfriends\nBut, you know\nWho understands those rap guys?\nThey only talk to her because she looks like a total prostitute\nI mean her butt\nIt's just so big\nI can't believe it's so round\nIt's just out there\nI mean, it's gross\nLook, she's just so black\n\nI like big butts and I can not lie\nYou other brothers can't deny\nThat when a girl walks in with an itty bitty waist\nAnd a round thing in your face\nYou get sprung\nWanna pull up tough\nCuz you notice that butt was stuffed\nDeep in the jeans she's wearing\nI'm hooked and I can't stop staring\nOh, baby I wanna get with ya\nAnd take your picture\nMy homeboys tried to warn me\nBut that butt you got\nMake Me so horney\nOoh, rump of smooth skin\nYou say you wanna get in my benz\nWell use me use me cuz you aint that average groupy\n\nI've seen them dancin'\nThe hell with romancin'\nShe's sweat, wet,\nGot it goin' like a turbo 'Vette\nI'm tired of magazines\nSaying flat butts are the thing\nTake the average black man and ask him that\nShe gotta pack much back\n...\n\n******* This Lyrics is NOT for Commercial use *******\n(1409618378968)")
Lyric.create(song_title: "All Star", genre:"Pop", artist:"Smash Mouth", api_id: 19098760, content:"Somebody once told me\nThe world is gonna roll me\nI ain't the sharpest tool in the shed\nShe was looking kinda dumb\nWith her finger and her thumb\nIn the shape of an \"L\" on her forehead\n\nWell, the years start coming\nAnd they don't stop coming\nFed to the rules and I hit the ground running\nDidn't make sense not to live for fun\nYour brain gets smart, but your head gets dumb\n\nSo much to do, so much to see\nSo what's wrong with taking the back streets?\nYou'll never know if you don't go\nYou'll never shine if you don't glow\n\nHey now, you're an all star\nGet your game on, go play\nHey now, you're a rock star\nGet the show on, get paid\nAnd all that glitters is gold\nOnly shooting stars break the mold\n\nIt's a cool place and they say it gets colder\nYou're bundled up now, wait 'til you get older\n...\n\n******* This Lyrics is NOT for Commercial use *******\n(1409618378968)")

UserLyric.create(user_id:1, lyric_id: 1, correct: true)
